// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package litrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LLMClient is the client API for LLM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMClient interface {
	// AnalyzeNode performs LLM analysis on the node's current state.
	AnalyzeNode(ctx context.Context, in *AnalyzeNodeRequest, opts ...grpc.CallOption) (*AnalyzeNodeResponse, error)
}

type lLMClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMClient(cc grpc.ClientConnInterface) LLMClient {
	return &lLMClient{cc}
}

func (c *lLMClient) AnalyzeNode(ctx context.Context, in *AnalyzeNodeRequest, opts ...grpc.CallOption) (*AnalyzeNodeResponse, error) {
	out := new(AnalyzeNodeResponse)
	err := c.cc.Invoke(ctx, "/litrpc.LLM/AnalyzeNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMServer is the server API for LLM service.
// All implementations must embed UnimplementedLLMServer
// for forward compatibility
type LLMServer interface {
	// AnalyzeNode performs LLM analysis on the node's current state.
	AnalyzeNode(context.Context, *AnalyzeNodeRequest) (*AnalyzeNodeResponse, error)
	mustEmbedUnimplementedLLMServer()
}

// UnimplementedLLMServer must be embedded to have forward compatible implementations.
type UnimplementedLLMServer struct {
}

func (UnimplementedLLMServer) AnalyzeNode(context.Context, *AnalyzeNodeRequest) (*AnalyzeNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeNode not implemented")
}
func (UnimplementedLLMServer) mustEmbedUnimplementedLLMServer() {}

// UnsafeLLMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServer will
// result in compilation errors.
type UnsafeLLMServer interface {
	mustEmbedUnimplementedLLMServer()
}

func RegisterLLMServer(s grpc.ServiceRegistrar, srv LLMServer) {
	s.RegisterService(&LLM_ServiceDesc, srv)
}

func _LLM_AnalyzeNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServer).AnalyzeNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/litrpc.LLM/AnalyzeNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServer).AnalyzeNode(ctx, req.(*AnalyzeNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLM_ServiceDesc is the grpc.ServiceDesc for LLM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "litrpc.LLM",
	HandlerType: (*LLMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeNode",
			Handler:    _LLM_AnalyzeNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lit-llm.proto",
}
