// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package litrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LLMClient is the client API for LLM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMClient interface {
	// AnalyzeNode performs LLM analysis on the node's current state.
	AnalyzeNode(ctx context.Context, in *AnalyzeNodeRequest, opts ...grpc.CallOption) (LLM_AnalyzeNodeClient, error)
}

type lLMClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMClient(cc grpc.ClientConnInterface) LLMClient {
	return &lLMClient{cc}
}

func (c *lLMClient) AnalyzeNode(ctx context.Context, in *AnalyzeNodeRequest, opts ...grpc.CallOption) (LLM_AnalyzeNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &LLM_ServiceDesc.Streams[0], "/litrpc.LLM/AnalyzeNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &lLMAnalyzeNodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LLM_AnalyzeNodeClient interface {
	Recv() (*AnalyzeNodeResponse, error)
	grpc.ClientStream
}

type lLMAnalyzeNodeClient struct {
	grpc.ClientStream
}

func (x *lLMAnalyzeNodeClient) Recv() (*AnalyzeNodeResponse, error) {
	m := new(AnalyzeNodeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LLMServer is the server API for LLM service.
// All implementations must embed UnimplementedLLMServer
// for forward compatibility
type LLMServer interface {
	// AnalyzeNode performs LLM analysis on the node's current state.
	AnalyzeNode(*AnalyzeNodeRequest, LLM_AnalyzeNodeServer) error
	mustEmbedUnimplementedLLMServer()
}

// UnimplementedLLMServer must be embedded to have forward compatible implementations.
type UnimplementedLLMServer struct {
}

func (UnimplementedLLMServer) AnalyzeNode(*AnalyzeNodeRequest, LLM_AnalyzeNodeServer) error {
	return status.Errorf(codes.Unimplemented, "method AnalyzeNode not implemented")
}
func (UnimplementedLLMServer) mustEmbedUnimplementedLLMServer() {}

// UnsafeLLMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServer will
// result in compilation errors.
type UnsafeLLMServer interface {
	mustEmbedUnimplementedLLMServer()
}

func RegisterLLMServer(s grpc.ServiceRegistrar, srv LLMServer) {
	s.RegisterService(&LLM_ServiceDesc, srv)
}

func _LLM_AnalyzeNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyzeNodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMServer).AnalyzeNode(m, &lLMAnalyzeNodeServer{stream})
}

type LLM_AnalyzeNodeServer interface {
	Send(*AnalyzeNodeResponse) error
	grpc.ServerStream
}

type lLMAnalyzeNodeServer struct {
	grpc.ServerStream
}

func (x *lLMAnalyzeNodeServer) Send(m *AnalyzeNodeResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LLM_ServiceDesc is the grpc.ServiceDesc for LLM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "litrpc.LLM",
	HandlerType: (*LLMServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzeNode",
			Handler:       _LLM_AnalyzeNode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lit-llm.proto",
}
