// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: lit-llm.proto

package litrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// query is the natural language query to analyze the node data.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *AnalyzeNodeRequest) Reset() {
	*x = AnalyzeNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lit_llm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzeNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeNodeRequest) ProtoMessage() {}

func (x *AnalyzeNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_llm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeNodeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeNodeRequest) Descriptor() ([]byte, []int) {
	return file_lit_llm_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeNodeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type AnalyzeNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// analysis contains the natural language analysis response.
	Analysis string `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
}

func (x *AnalyzeNodeResponse) Reset() {
	*x = AnalyzeNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lit_llm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzeNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeNodeResponse) ProtoMessage() {}

func (x *AnalyzeNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_llm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeNodeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeNodeResponse) Descriptor() ([]byte, []int) {
	return file_lit_llm_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeNodeResponse) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

var File_lit_llm_proto protoreflect.FileDescriptor

var file_lit_llm_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x69, 0x74, 0x2d, 0x6c, 0x6c, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x6c, 0x69, 0x74, 0x72, 0x70, 0x63, 0x22, 0x2a, 0x0a, 0x12, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x7a, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x22, 0x31, 0x0a, 0x13, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x32, 0x4d, 0x0a, 0x03, 0x4c, 0x4c, 0x4d, 0x12, 0x46, 0x0a,
	0x0b, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x2e, 0x6c,
	0x69, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x69, 0x74, 0x72, 0x70,
	0x63, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x69, 0x6e, 0x67, 0x6c, 0x61, 0x62,
	0x73, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x69, 0x6e, 0x67, 0x2d, 0x74, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x2f, 0x6c, 0x69, 0x74, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_lit_llm_proto_rawDescOnce sync.Once
	file_lit_llm_proto_rawDescData = file_lit_llm_proto_rawDesc
)

func file_lit_llm_proto_rawDescGZIP() []byte {
	file_lit_llm_proto_rawDescOnce.Do(func() {
		file_lit_llm_proto_rawDescData = protoimpl.X.CompressGZIP(file_lit_llm_proto_rawDescData)
	})
	return file_lit_llm_proto_rawDescData
}

var file_lit_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lit_llm_proto_goTypes = []any{
	(*AnalyzeNodeRequest)(nil),  // 0: litrpc.AnalyzeNodeRequest
	(*AnalyzeNodeResponse)(nil), // 1: litrpc.AnalyzeNodeResponse
}
var file_lit_llm_proto_depIdxs = []int32{
	0, // 0: litrpc.LLM.AnalyzeNode:input_type -> litrpc.AnalyzeNodeRequest
	1, // 1: litrpc.LLM.AnalyzeNode:output_type -> litrpc.AnalyzeNodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lit_llm_proto_init() }
func file_lit_llm_proto_init() {
	if File_lit_llm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lit_llm_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AnalyzeNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lit_llm_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AnalyzeNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lit_llm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lit_llm_proto_goTypes,
		DependencyIndexes: file_lit_llm_proto_depIdxs,
		MessageInfos:      file_lit_llm_proto_msgTypes,
	}.Build()
	File_lit_llm_proto = out.File
	file_lit_llm_proto_rawDesc = nil
	file_lit_llm_proto_goTypes = nil
	file_lit_llm_proto_depIdxs = nil
}
